# check_openshift.yml
---
- name: openshift_project should be defined
  assert:
    that:
      - openshift_project is defined and openshift_project != ''
    msg: "Set the value of 'openshift_project' in the inventory file."

- name: openshift_user should be defined
  assert:
    that:
      - openshift_user is defined and openshift_user != ''
    msg: "Set the value of 'openshift_user' in the inventory file."

- name: openshift_password or openshift_token should be defined
  assert:
    that:
      - (openshift_password is defined and openshift_password != '') or
        (openshift_token is defined and openshift_token != '')
    msg: "Set the value of 'openshift_password' or 'openshift_token' in the inventory file."

- name: container_registry should be defined if not using dockerhub
  assert:
    that:
      - container_registry is defined and container_registry != ''
    msg: "Set the value of 'container_registry' in the inventory file."
  when: dockerhub_base is not defined

- name: container_registry_repository should be defined if not using dockerhub
  assert:
    that:
      - container_registry_repository is defined and container_registry_repository != ''
    msg: "Set the value of 'container_registry_repository' in the inventory file."
  when: dockerhub_base is not defined

- name: container_registry_username should be defined if not using dockerhub
  assert:
    that:
      - container_registry_username is defined and container_registry_username != ''
    msg: "Set the value of 'container_registry_username' in the inventory file."
  when: dockerhub_base is not defined

- name: container_registry_password should be defined
  assert:
    that:
      - container_registry_password is defined and container_registry_password != ''
    msg: "Set the value of 'container_registry_password' in the inventory file."
  when: dockerhub_base is not defined
