# main.yml
---
- include_tasks: check_openshift.yml
  when: openshift_host is defined and openshift_host != ''

- include_tasks: check_container.yml
  when: openshift_host is not defined or openshift_host == ''
