---
- name: Authenticate with container registry if registry password given (docker)
  docker_login:
    registry: "{{ container_registry }}"
    username: "{{ container_registry_username }}"
    password: "{{ container_registry_password }}"
    reauthorize: true
  when: container_registry is defined and container_registry_password is defined and (container_runtime == 'docker')
  delegate_to: localhost

- name: Authenticate with container registry if registry password given (podman)
  shell: "podman login -u {{ container_registry_username }} -p {{ container_registry_password }} {{ container_registry }}"
  when: container_registry is defined and container_registry_password is defined and (container_runtime == 'podman')
  delegate_to: localhost

- name: Remove local images to ensure proper push behavior (docker)
  block:
    - name: Remove awx image
      docker_image:
        name: "{{ container_registry }}/{{ container_registry_repository }}/{{ awx_image }}"
        tag: "{{ awx_version }}"
        state: absent
  when: container_runtime == 'docker'
  delegate_to: localhost

- name: Remove local images to ensure proper push behavior (podman)
  block:
    - name: Remove awx image
      containers.podman.podman_image:
        name: "{{ container_registry }}/{{ container_registry_repository }}/{{ awx_image }}:{{ awx_version }}"
        state: absent
  when: container_runtime == 'podman'
  delegate_to: localhost

- name: Tag and Push Container Images
  block:
    - name: Tag and push awx image to registry (docker)
      docker_image:
        name: "{{ awx_image }}"
        repository: "{{ container_registry }}/{{ container_registry_repository }}/{{ awx_image }}"
        tag: "{{ item }}"
        push: true
      with_items:
        - "latest"
        - "{{ awx_version }}"
  when: container_runtime == 'docker'
  delegate_to: localhost

- name: Tag and Push Container Images (podman)
  block:
    - name: Tag and push awx image to registry (podman)
      containers.podman.podman_image:
        name: "{{ awx_image }}"
        repository: "{{ container_registry }}/{{ container_registry_repository }}/{{ awx_image }}:{{ item }}"
        push: true
      with_items:
        - "latest"
        - "{{ awx_version }}"
  when: container_runtime == 'podman'
  delegate_to: localhost

- name: Set full image path for Registry
  set_fact:
    awx_container_actual_image: >-
      {{ container_registry }}/{{ container_registry_repository }}/{{ awx_image }}:{{ awx_version }}
