---
- name: Build and deploy AWX
  hosts: all
  roles:
    - {role: check_vars}
    - {role: image_build, when: "containerhub_base is not defined"}
    - {role: image_push, when: "container_registry is defined and containerhub_base is not defined"}
    - {role: kubernetes, when: "openshift_host is defined or kubernetes_context is defined"}
    - {role: local_container, when: "openshift_host is not defined and kubernetes_context is not defined"}
